### ISSUE TITLE
Tracking: JavaScript (Node.js) Module

### ISSUE THREAD

**Issue by aj-ptw** [VisLab/HEDTools#21]
I need a port of this for in JavaScript (Node.js package) environment

Are there plans for this?

**Comment by jcockfie** [comment]
This is spam

**Comment by aj-ptw** [comment]
This was now spam, it was for sure a serious request for a NPM (module) of HEDTools

**Comment by aj-ptw** [comment]
I use HEDTags all the time and have had to write a bunch of code to make them work well in pure JS and pure Python.
