### ISSUE TITLE
Bug with Action/Eye open/Keep/With blinking tag requiring unit

### ISSUE THREAD

**Issue by Theendeavorer** [VisLab/HEDTools#46]
There is an issue with validating for this tag. Keep is requiring a value even though it is optional.

Here is the error:
Issues on line 2: 	ERROR: Invalid unit (pick one of units "s,second,seconds,centoseconds,hour:min,day,days,ms,milliseconds,minute,minutes,hour,hours") - "Action/Eye open/Keep/With blinking" 

And here is what HED Schema says:
Eye open [Open eyes and keep open for more than approximately 0.1 s]
Keep [Keep the eye open. **_If a value is provided it indicates the duration for this._**]
...
With blinking [Default. Allow blinking during the eye-open period.]
Without blinking [Without blinking during the eye-open period.]

The tsv file is in the email. I used validatetsv as shown in the image below to generate the error.
![validatetsv bug](https://cloud.githubusercontent.com/assets/18445974/23671663/b77c8560-0331-11e7-85b3-ee9bb8c59a80.jpg)

**Comment by jcockfie** [comment]
Fixed!!! Will be in next release.
