### ISSUE TITLE
Conversion of Reward Two-Back CPT from HED1/ESS1 to HED2/ESS2

### ISSUE THREAD

**Issue by VisLab** [VisLab/HEDTools#8]
Pending: review of tags

**Comment by VisLab** [comment]
Tags have been approved.

**Comment by VisLab** [comment]
Data issues to be resolved:

1.  Files will need to be converted to .set
2.  There are many spurious event codes that need to be removed.
3.  The channel location files do not agree with the channels

Once this is done, we can proceed with the ESS conversion --- do we need a separate recording parameter set for each file.

**Comment by jcockfie** [comment]
This is being moved to a separate repository.
